default_language_version:
    python: python3.10
repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-yaml
        args:
        -   --unsafe
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: git@github.com:asottile/pyupgrade.git
    rev: v3.7.0
    hooks:
    -   id: pyupgrade
        args:
        - --py3-plus
        - --keep-runtime-typing
-   repo: git@github.com:astral-sh/ruff-pre-commit.git
    rev: v0.0.275
    hooks:
    -   id: ruff
        args:
        - --fix
-   repo: git@github.com:psf/black.git
    rev: 23.3.0
    hooks:
    -   id: black
